//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITDevelopment_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceSet
    {
        public int Id { get; set; }
        public int Gain { get; set; }
        public int Costs { get; set; }
        public System.DateTime Date { get; set; }
        public string Profit { get; set; }
    }
}
