//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITDevelopment_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITDevelopmentEntities : DbContext
    {
        public ITDevelopmentEntities()
            : base("name=ITDevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttedenceSet> AttedenceSet { get; set; }
        public virtual DbSet<ClientSet> ClientSet { get; set; }
        public virtual DbSet<CustomSet> CustomSet { get; set; }
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<FinanceSet> FinanceSet { get; set; }
        public virtual DbSet<PersonalSet> PersonalSet { get; set; }
        public virtual DbSet<SeminarsSet> SeminarsSet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
